### PR TITLE
Disable highlighting of julia-0.3 consts after qualification

### PR DESCRIPTION
**Pull request by c42f**
Do not highlight Base global variables such as DL_LOAD_PATH as julia-0.3 syntax unless they're unqualified names (ie, not prefixed with a '.' character).  For example, this prevents the highlighting of the second part of Libdl.DL_LOAD_PATH as deprecated syntax in julia-0.4.

The affected consts now live in modules: Base.Libdl, Base.Mmap.

### CODE REVIEW

**Comment by carlobaldassi** [comment]
Sorry for the delay. I'm torn about this solution because of performance issues with the `\@<!` regex directive and the fact that it should probably be prepended to all types if we were to do things correctly.

I'm currently leaning towards disabling the deprecation highlighting instead, and only activating it on request, which I also think is consistent with the plugin not doing the job of a linter.

**Comment by c42f** [comment]
Sounds reasonable, I'm certainly not an expert on performance implications of the highlighting setup.

As an alternative, could we turn the negative assertion into a positive one (deprecated names being preceded by either whitespace or start of line)? Presumably that wouldn't have the same performance penalty and would work in nearly all cases?

**Comment by carlobaldassi** [comment]
So I made the highlighting of deprecated items optional, even though it just hides the problem somehow and the correct solution would be more along the lines of this PR. Unfortunately, a "positive assertion" is not really a viable alternative, because there are too many possibilities of what could precede a valid identified (besides whitespace and start of a line, there are all sorts of symbols like open brackets, operators etc.)

In my `.vimrc`, I added this mapping, you may find it useful:

```
noremap <expr> <S-F6> julia#toggle_deprecated_syntax()
```

(also use `let g:julia_syntax_highlight_deprecated = 1` to opt-in by default.)

**Comment by c42f** [comment]
Ok, thanks for cleaning this up.  It's not clear what a really good solution would look like in this case, it seems we're reaching the boundary of what can reasonably be done with regexes.

**Pull request closed without merging**
